<%@page contentType="text/html" import="no.vianett.sms.component.SmsTransceiver,no.vianett.sms.Sms,no.vianett.sms.log.SmsSinkLogger" %>
<html>
	<head>
		<title>JSP with SMS</title>
	</head>

	<body>
		<%
			SmsTransceiver transceiver = SmsTransceiver.getInstance();
		
			// Initialise SMS transceiver if this hasn't been done before.
			if( !transceiver.isInitialized() )
			{
			      String smsHost = "cpa.vianett.no";
			      String smsPort = "31337";
			      String smsUsername = "psdhillon111@gmail.com";
			      String smsPassword = "dhillon92";
			      
			      transceiver.initialize( smsHost, Integer.parseInt( smsPort ), smsUsername, smsPassword, new SmsSinkLogger() ); // No logging.
			}
		
			// Send SMS
			Sms sms = new Sms();
			sms.setId(1068); // This ID number should be generated by the application.
			sms.setSender( "1968" );
			sms.setRecipient("12105733017");
			//sms.setRecipient("919023968755");
			sms.setMessage( "Ajeet Test Barbara Demo New00" );	
			transceiver.send( sms );
		%>
			SMS enqued for sending.
	</body>
</html>